### ISSUE TITLE
Workflow file-ok javítása

### ISSUE THREAD

**Issue by sarvarimark** [csertant/szikapp#24]
Azért nem csinálnám még, mert lehet hogy patchek fognak érkezni, de addig is az összes GitHub Actionünk el fog hasalni.
Nem kellene őket leállítani addig is?

**Comment by csertant** [comment]
Szerintem azért jó, ha futnak, mert látjuk, hogy mik a hibák. Ráadásul publikus repóban nem számítanak a build minute-ek.

**Comment by sarvarimark** [comment]
Ha írsz egy branch nevet megcsinálhatom.
hotfix-worflow-to-flutter2?

**Comment by sarvarimark** [comment]
Plusz akkor már ezt is frissítsük: https://github.com/csertant/szikapp/blob/56e73da87feae87fb430ab61870631e14a0852ea/pubspec.yaml#L11
