### ISSUE TITLE
Akadálymentesség

### ISSUE THREAD

**Issue by csertant** [csertant/szikapp#3]
Érdemes erre figyelnünk.
Elvileg most is van a koliban színvak és színtévesztő, de jobb, ha gondolunk mindenre, ami előfordulhat.
Alapvetően teszteket lehet futtatni, amikből kiderül, hogy jók-e az alapvetések és ott beavatkozni, ahol kell; emellett a dizájn tervezés során szem előtt tartani bizonyos jellemzőket (nagy betűméretek, érzékelhető kontrasztkülönbségek).

**Comment by sarvarimark** [comment]
https://color.adobe.com/create/color-accessibility

**Comment by csertant** [comment]
Too fancy; not priority.
Visszatérhetünk rá az MVP elkészülte után.
