### ISSUE TITLE
Reszponzivitás

### ISSUE THREAD

**Issue by sarvarimark** [csertant/szikapp#53]
Ez egy felsorolás azon widgetekről amelyek nem reszponzívak - azaz nem a képernyő százalékában, hanem konkrét pixelértékek alapján méretezik magukat.
- [ ] SubMenuPage
- [ ] Ikonok (jelenleg 72x72)
- [ ] Foglalások játéklista

**Comment by csertant** [comment]
A jövőre nézve: amelyik lapon látszik a **bottomNavigationBar** ott a **MediaQuery**-ből kért méretekből le kell vonni a **kBottomNavigationBarHeight** konstans értékét, hogy a képernyő ne lógjon rá a navBarra.
https://stackoverflow.com/a/57643641

**Comment by sarvarimark** [comment]
Refaktor ezzel?
https://pub.dev/packages/flutter_screenutil

**Comment by csertant** [comment]
Kellene, főleg, hogy a betűtípusok úgy látszik törnek bizonyos képernyőkön.
