### ISSUE TITLE
Janitor filter

### ISSUE THREAD

**Issue by sarvarimark** [csertant/szikapp#78]
A Janitor osztály filter függvényéből kimaradt az a szűrési lehetőség, hogy azokat láthassam, amik engem érintenek.
API oldalon implementálva van, csak a kliensből kimaradt. Az 'initiator' paramétert kell a böngésző user id-jával párosítani.

**Comment by csertant** [comment]
Talán ezt is érdemes lokálisan szűrni. Erre az esetre [megoldás](https://github.com/csertant/szikapp/commit/290fd12f1b716c954a5ed9e90a72063d48f9d3c5).
