### ISSUE TITLE
Internet hozzáférés kezelés/ellenőrzés

### ISSUE THREAD

**Issue by sarvarimark** [csertant/szikapp#83]
Mivel az app jelen állapotában teljes mértékben függ az internetkapcsolattól, célszerű lenne betöltés után rögtön ellenőrizni, hogy online van-e a felhasználó, megelőzve a Google Sign In API azonnali hibáját.
Praktikusan ezzel: https://pub.dev/packages/connectivity

**Comment by csertant** [comment]
Előzetes megoldás kész a [connectivity_plus](https://pub.dev/packages/connectivity_plus) plugint használva.

FONTOS! A plugin Androidon nem feltétlenül jelzi helyesen az internetkapcsolat meglétét, lásd [itt](https://pub.dev/packages/connectivity#-readme-tab-).
Ha jobb megoldás kell, érdemes lesz majd:
- [saját megoldás](https://stackoverflow.com/a/53855326)t írni
- használni a [DataConnectionChecker](https://pub.dev/packages/data_connection_checker) package-t
