### ISSUE TITLE
Szövegbeviteli probléma a bottomNavigationból közvetlenül megnyitott oldalakon

### ISSUE THREAD

**Issue by csertant** [csertant/szikapp#88]
A Flutter framework rejtélyes hibája előjön az appban, mikor a `PersistentBottomNavBar`ban közvetlenül kiválasztott tabokon szeretnénk szövegmezőt szerkeszteni. Ilyenkor a billentyűzet egy pillanatra megjelenik, de a layout azonnal újrabuildeli magát, ezáltal a `TextField` elveszíti a fókuszt; nem is lehet bele írni ilyen állapotban.
A probléma nem jelentkezik, ha a `NavBar`ban kiválasztott oldalról a `Navigator` segítségével már másik lapra routeoltunk.

Amíg a [Flutter issue #9471](https://github.com/flutter/flutter/issues/9471) nem oldódik meg nincs mit tenni.
**Ideiglenes megoldás:**
*Nem használhatunk `NavBar` oldalként olyan lapot, amin található szerkeszthető `TextField`.*

**Jövőre nézve:**

- érdemes kipróbálni kibékíteni a [navigációt a NavBarral](https://pub.dev/packages/persistent_bottom_nav_bar#navigator-functions).
- vagy kiszedni az összes `MediaQuery.of(context)` hívást a widgetből
- vagy a két szélső NavBar gomb egy üres lapot ad vissza, ami rögvest átirányít egy funkcióval rendelkező lapra.

**Comment by sarvarimark** [comment]
A Navigation 2.0 megoldotta, mivel új típusu bottomnavbar készült.
