### ISSUE TITLE
Beépített vissza gomb

### ISSUE THREAD

**Issue by csertant** [csertant/szikapp#94]
A visszajelzések alapján érdemes megvizsgálni a lehetőséget, hogy beépítsünk egy szoftveres vissza gombot az appba (vannak telefonok, ahol amúgy sincs hardveres vissza gomb és az iOS style back swipe sem működik / nem eléggé intuitív).

Elképzelések:

- [ ] bal felső sarok vissza nyíl
- [ ] alsó tab navigáció egyik "gombja" (#88 miatt amúgy is ki kell találnunk, miket tehetünk ide)

**Comment by sarvarimark** [comment]
A #88 miatt is próbáljuk meg az alábbi beosztást:
Szoftveres vissza gomb - Menü - Feed

**Comment by csertant** [comment]
Sajnos az alsó menüben nem fog tudni működni a vissza gomb, mert a TabNavigation csak oldalakat tud kezelni, függvényeket nem lehet mögé tenni.

**Comment by sarvarimark** [comment]
Költöztetve Meistertaskba
